spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-S68UFCF;encrypt=true;trustServerCertificate=true;databaseName=prog3170_finalExam
    username: sa
    password: Secret55
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080